### ISSUE TITLE
Add a interface to choose different Promise, will be better

### ISSUE THREAD

**Issue by machinewu** [IvanDimanov/paratask-promises#1]
If you write a interface to choose a different Promise(e.g. bluebird/Q/others), I think it will be better.

**Comment by IvanDimanov** [comment]
Hi @machinewu 
Thanks for the good idea.
Which one do you prefer:

1) global.Promise = require('bluebird');
or
2) var paratask = require('paratask-promise');
    paratask.use( require('bluebird') );

All ideas are highly welcome :)

**Comment by machinewu** [comment]
I think 2 is better, because I can change anywhere I want.

**Comment by IvanDimanov** [comment]
The client is always right :)
Will work on it this weekend, update the README, and hopefully will put it online early next week.
Will inform you once done

**Comment by machinewu** [comment]
Hey, any good news of new version? Looking forward!

**Comment by IvanDimanov** [comment]
Hi @machinewu 
Really sorry for the huge delay ... got tons of stuff ...
The feature is shipped and ready :)
I named it "usePromise" to be explicit.

Thanks again for the ping.
I mentioned you in the readme, If you don't like it - I'll remove your name.

Take care
